config/routes.rb
Rails.application.routes.draw do

  resources :reviews do
    resources :comments
    resource :bookmark
  end

  resources :users

  resource :session

  root "reviews#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :review
  belongs_to :user

  validates :review, uniqueness: { scope: :user }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :review
  belongs_to :user

  profanity_filter :body

  validates :body, presence: true
end

app/models/review.rb
class Review < ApplicationRecord

    has_many :comments
    has_many :bookmarks

    belongs_to :user

    geocoded_by :address
    after_validation :geocode

    validates :title, presence: true
    validates :body, length: { minimum: 10 }
    validates :score, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
    validates :restaurant, presence: true
    validates :address, presence: true

    def to_param
        id.to_s + "-" + title.parameterize
    end

end

app/models/user.rb
class User < ApplicationRecord

    has_many :comments
    has_many :reviews
    has_many :bookmarks
    
    has_secure_password

    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true

    def to_param
        username
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :find_current_user

    helper_method :is_logged_in?

    def find_current_user
        if is_logged_in?
            @current_user = User.find(session[:user_id])
        else
            @current_user = nil
        end
    end

    def check_login
        if is_logged_in?

        else
            redirect_to new_session_path
        end
    end

    def is_logged_in?
        session[:user_id].present?
    end

end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
    before_action :check_login

    def show
        @review = Review.find(params[:review_id])
        @bookmark = @review.bookmarks.where(user: @current_user)
    end
    
    def create
        @review = Review.find(params[:review_id])

        @bookmark = @review.bookmarks.new
        @bookmark.user = @current_user

        @bookmark.save

        redirect_to review_path(@review)
    end

    def destroy
        @review = Review.find(params[:review_id])

        @review.bookmarks.where(user: @current_user).delete_all

        redirect_to review_path(@review)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @review = Review.find(params[:review_id])

        @comment = @review.comments.new(params.require(:comment).permit(:body))
        @comment.user = @current_user
        @comment.save
        redirect_to review_path(@review)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :check_login, except: [:index, :show]

    def index
        @price = params[:price]
        @cuisine = params[:cuisine]
        @location = params[:location]
   
        @reviews = Review.all

        if @price.present?
            @reviews = @reviews.where(price: @price)
        end

        if @cuisine.present?
            @reviews = @reviews.where(cuisine: @cuisine)
        end

        if @location.present?
            @reviews = @reviews.near(@location)
        end

    end

    def new
        @review = Review.new
    end

    def create
        #grab info from form
        @review = Review.new(form_params)
        @review.user = @current_user

        #save to model
        if @review.save
            redirect_to root_path
        else
            render "new"
        end  

    end

    def show
        @review = Review.find(params[:id])
    end

    def edit
        @review = Review.find(params[:id])

        if @review.user != @current_user
            redirect_to root_path
        end
    end

    def update
        @review = Review.find(params[:id])

        if @review.user != @current_user
            redirect_to root_path
        else 
            if @review.update(form_params)
                redirect_to review_path(@review)
            else
                render "edit"
            end
        end
    end

    def destroy
        @review = Review.find(params[:id])

        if @review.user == @current_user
            @review.destroy
        end

        redirect_to root_path
    end

    def form_params
        params.require(:review).permit(:title, :restaurant, :body, :score, :price, :cuisine, :ambiance, :address, :phone_number)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    # def new
    #     #form
    #     @session = Session.new
    # end

    def create
        @form_data = params.require(:session)

        @username = @form_data[:username]
        @password = @form_data[:password]

        @user = User.find_by(username: @username).try(:authenticate, @password)

        if @user
            session[:user_id] = @user.id
            redirect_to root_path
            else
                render "new"
        end
    end

    def destroy
        reset_session
        redirect_to new_session_path, status: :see_other
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index
        @users = User.all
    end

    def show
        @user = User.find_by(username: params[:id])
    end
        
    def new
        @user = User.new
    end

    def create
        @user = User.new(form_params)

        if @user.save
            session[:user_id] = @user.id
            
            redirect_to users_path
        else
            render "new"
        end
    end

    def form_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/show.html.erb
BOOKMARK!

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for :page_title %> - Bien Reviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav>
        <h1>
          <%= link_to root_path do %>
            <%= image_tag "bien-logo.svg" %>
          <% end %>
        </h1>
      </nav>
      <nav>
        The best restaurant reviews in the world 🌎
      </nav>
      <nav>
        <% if is_logged_in? %>
            <%= @current_user.username %>
            <%= link_to "Add a review", new_review_path %>
            <%= link_to "Log out", session_path, data: { turbo_method: :delete } %>
          <% else %>
            <%= link_to "Sign up", new_user_path %>
            <%= link_to "Log in", new_session_path %>
        <% end %>
      </nav>
    </header>

    <%= yield %>

    <footer>
      <p>Copyright 2022 Bien Reviews</p>
    </footer>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for @review, data: { turbo: false } do |f| %>
    <%= f.input :title %>
    <%= f.input :restaurant %>
    <%= f.input :body %>
    <%= f.input :score %>
    <%= f.input :price %>
    <%= f.input :cuisine %>
    <%= f.input :ambiance %>
    <%= f.input :address %>
    <%= f.input :phone_number %>

    <%= f.button :submit %>
<% end %>

app/views/reviews/edit.html.erb
<h3>Edit your restaurant review</h3>

<%= render "form" %>

app/views/reviews/index.html.erb
<% content_for :page_title, "Homepage" %>

<nav class="filters">
    <%= active_link_to "All reviews", root_path, active: { price: nil, cuisine: nil, location: nil } %>
    <%# Price:  %>
    <div>
        <%= active_link_to "$", root_path(price: 1, cuisine: @cuisine), active: { price: 1 } %>
        <%= active_link_to "$$", root_path(price: 2, cuisine: @cuisine), active: { price: 2 } %>
        <%= active_link_to "$$$", root_path(price: 3, cuisine: @cuisine), active: { price: 3 } %>
    </div>
    <%# Cuisine:  %>
    <div>
        <%= active_link_to "Indian", root_path(cuisine: "Indian", price: @price), active: { cuisine: "Indian" } %>
        <%= active_link_to "Vietnamese", root_path(cuisine: "Vietnamese", price: @price), active: { cuisine: "Vietnamese" } %>
        <%= active_link_to "Mexican", root_path(cuisine: "Mexican", price: @price), active: { cuisine: "Mexican" } %>
    </div>
    <form action="/">
        <input type="text" name="location" placeholder="Search location..." value="<%= @location %>">
    </form>
</nav>

<% @reviews.each do |review| %>
    <div class="review">
        <%= link_to review_path(review) do %>
            <h2><%= review.title %></h2>
            <p>
                <% if review.cuisine.present? %>
                    <%= review.cuisine %>  - 
                    <% else %>
                        <%= "" %>
                <% end %>
                <%= pluralize review.comments.count, "comment" %>
            </p>
        <% end %>
    </div>
<% end %>

app/views/reviews/new.html.erb
<% content_for :page_title, "Add a new review" %>

<h3>Add a new restaurant review</h3>

<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for :page_title, @review.title %>

<h1><%= @review.title %></h1>
<h2><%= @review.restaurant %></h2>

<p>
    <% if is_logged_in? %>
        <% if @review.bookmarks.where(user: @current_user).any? %>
            <%= link_to "Unbookmark", review_bookmark_path(@review), method: :delete %>
        <% else %>
            <%= link_to "Bookmark", review_bookmark_path(@review), method: :post %>
        <% end %>
    <% end %>
</p>

<h3>Bookmarked by:</h3>
<ul>
    <% @review.bookmarks.each do |bookmark| %>
       <li><%= bookmark.user.username %></li> 
    <% end %>
</ul>

<div class="user">
    Posted by
        <%if @review.user.present? %>
            <%= link_to @review.user.username, user_path(@review.user) %>
        <% else %>
            Anonymous
        <% end %>
</div>

<div class="score">
    Score: <%= @review.score %> out of 10
</div>

<% if @review.price.present? %>
    <div class="price">
        Price: <%=  @review.price %>
    </div>
<% end %>

<% if @review.cuisine.present? %>
    <div class="cuisine">
        Cuisine: <%=  @review.cuisine %>
    </div>
<% end %>

<% if @review.ambiance.present? %>
    <div class="ambiance">
        Ambiance: <%= @review.ambiance %>
    </div>
<% end %>

<div class="address">
    Address: <%=  @review.address %>
</div>

<% if @review.phone_number.present? %>
    <div class="phone_number">
        Phone: <%=  @review.phone_number %>
    </div>
<% end %>

<div class="body">
    <%= simple_format @review.body %>
</div>

<% if @review.user == @current_user %>
    <div class="actions">
        <%= link_to "Edit", edit_review_path(@review) %>
        <%= button_to "Delete", review_path(@review), method: :delete, onclick: "return confirm('Are you sure you want to delete the review forever?')" %>
    </div>
<% end %>

<h3>Comments</h3>
    <% if @review.comments.present? %> 
        <% @review.comments.order("created_at desc").each do |comment| %>
            <div class="comment">
                <%= simple_format comment.body %>
                <p class="posted"> 
                    Posted by 
                    <% if comment.user.present? %>
                        <%= link_to comment.user.username, user_path(comment.user) %>
                    <% else %>
                        Anonymous
                    <% end %>
                </p>
                <p class="posted"><%= time_ago_in_words comment.created_at %> ago</p>
            </div>
        <% end %>
    <% else %>
        <p class="comment"> No comments yet. Be the first to leave one below.</p>
    <% end %> 

<h3>Add a comment</h3>
<%= simple_form_for [@review, Comment.new] do |f| %>
    <%= f.input :body %>
    <%= f.button :submit, "Add comment" %>
<% end %>

app/views/users/_form.html.erb
<%= simple_form_for @user, data: { turbo: false } do |f| %>
    <%= f.input :username %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>

    <%= f.button :submit, "Sign up" %>
<% end %>

app/views/users/index.html.erb
<h2>All users</h2>

<% @users.each do |user| %>
    <p>
        <%= user.username %> (<%= user.email%>)
    </p>
<% end %>

app/views/users/new.html.erb
<% content_for :page_title, "Sign up" %>

<h3>Create account</h3>

<%= render "form" %>

app/views/users/show.html.erb
<h2><% @user.username %></h2>
<p>Email: <%= @user.email %></p>